/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#b8e6e2",
        "on-primary-fixed": "#154240",
        "on-tertiary-fixed-variant": "#4d606b",
        "surface-bright": "#faf9f6",
        "surface-variant": "#e1e3df",
        "inverse-on-surface": "#9d9d9a",
        "secondary-dim": "#5f531a",
        "on-primary-fixed-variant": "#345f5c",
        "surface-container-high": "#e8e8e4",
        "on-secondary": "#fff8eb",
        "background": "#faf9f6",
        "primary-dim": "#2f5a57",
        "outline-variant": "#b1b2af",
        "inverse-primary": "#cffdf8",
        "on-primary-container": "#2a5553",
        "error": "#aa371c",
        "on-surface": "#303330",
        "error-dim": "#821a01",
        "outline": "#797b78",
        "inverse-surface": "#0d0f0d",
        "tertiary-container": "#d4e8f6",
        "primary-fixed": "#b8e6e2",
        "on-tertiary-container": "#435661",
        "error-container": "#fa7150",
        "on-tertiary": "#f4faff",
        "on-error": "#fff7f6",
        "tertiary-fixed": "#d4e8f6",
        "surface-container-highest": "#e1e3df",
        "surface-container-low": "#f4f4f0",
        "secondary-container": "#f7e59d",
        "primary-fixed-dim": "#abd7d3",
        "on-secondary-fixed": "#4c4108",
        "on-surface-variant": "#5d605c",
        "surface": "#faf9f6",
        "on-error-container": "#671200",
        "tertiary-fixed-dim": "#c6dae8",
        "surface-container": "#eeeeea",
        "on-secondary-container": "#5f531a",
        "on-secondary-fixed-variant": "#695d23",
        "surface-tint": "#3c6663",
        "tertiary": "#4f626d",
        "on-tertiary-fixed": "#31434e",
        "on-background": "#303330",
        "tertiary-dim": "#435661",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#f7e59d",
        "secondary": "#6b5f25",
        "primary": "#3c6663",
        "surface-dim": "#d9dbd6",
        "secondary-fixed-dim": "#e9d791",
        "on-primary": "#e1fffc",

        canopy: {
          bg: "#faf9f6",
          surface: "rgba(255, 255, 255, 0.4)",
          "surface-hover": "rgba(255, 255, 255, 0.6)",
          "surface-raised": "rgba(255, 255, 255, 0.8)",
          accent: "#3c6663",
          "accent-bright": "#b8e6e2",
          text: "#3c6663", // The primary green instead of #F0FDF4 white font
          "text-muted": "#5d605c",
          "text-dim": "#9d9d9a",
          border: "rgba(177, 178, 175, 0.2)",
          active: "#3c6663",
          sleeping: "#797b78",
          thinking: "#f7e59d",
          warning: "#fa7150",
          danger: "#aa371c",
          isolated: "#d4e8f6",
        },
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        sans: ["Manrope", "system-ui", "-apple-system", "sans-serif"],
        heading: ["Noto Serif", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      animation: {
        breathe: "breathe 4s ease-in-out infinite",
        pulse: "pulse 3s ease-in-out infinite",
        "glow-pulse": "glowPulse 2s ease-in-out infinite",
        "flow-dash": "flowDash 2s linear infinite",
        "float-up": "floatUp 5s ease-in-out infinite",
        "fade-slide-up": "fadeSlideUp 0.4s ease-out both",
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.004)" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 8px rgba(52,211,153,0.15)" },
          "50%": { boxShadow: "0 0 20px rgba(52,211,153,0.3)" },
        },
        flowDash: {
          to: { strokeDashoffset: "-20" },
        },
        floatUp: {
          "0%": { transform: "translateY(0) scale(1)", opacity: "0.15" },
          "50%": { opacity: "0.25" },
          "100%": { transform: "translateY(-30px) scale(0.5)", opacity: "0" },
        },
        fadeSlideUp: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
