use chrono::Utc;
use rusqlite::{params, Connection, OptionalExtension, Result as SqlResult};
use serde_json::json;
use std::sync::Mutex;
use tauri::Manager;
use uuid::Uuid;

use crate::models::*;

// ─── Local Models for DB Layer ───────────────────────────────────────────────

/// Represents an item in the user's universal inbox
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct InboxItem {
    pub id: String,
    pub item_type: String,
    pub status: String,
    pub payload_json: String,
    pub timestamp: String,
}

/// Represents a message in a conversation
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Message {
    pub id: String,
    pub conversation_id: String,
    pub role: String, // "user", "assistant", "system"
    pub content: String,
    pub timestamp: String,
}

/// Lightweight thread metadata for frontend hydration and recovery.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ConversationSummary {
    pub id: String,
    pub agent_id: String,
    pub title: String,
    pub created_at: String,
    pub updated_at: String,
    pub message_count: u32,
    pub first_user_message: Option<String>,
}

/// Represents an audit log entry
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AuditEntry {
    pub id: u32,
    pub timestamp: String,
    pub agent_id: Option<String>,
    pub action: String,
    pub bridge_type: Option<String>,
    pub detail: String,
    pub content_hash: Option<String>,
}

/// Represents an aggregated activity count per day for a heatmap
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ActivityHeatmapEntry {
    pub date: String,
    pub interactions: u32,
    pub tools: u32,
    pub system: u32,
    pub total: u32,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BrowserHistoryEntry {
    pub timestamp: String,
    pub action: String,
    pub detail: String,
}

/// Represents a security alert generated by the network sniffer
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SecurityAlert {
    pub id: String,
    pub agent_id: String,
    pub timestamp: String,
    pub severity: String, // "Medium", "High", "Critical"
    pub description: String,
    pub resolved: bool,
}

// ─── Database Struct ─────────────────────────────────────────────────────────

/// Thread-safe SQLite database wrapper for Canopy
pub struct Database {
    conn: Mutex<Connection>,
}

impl Database {
    /// Initialize the database, creating tables and migrations as needed
    pub fn init<R: tauri::Runtime>(app_handle: &tauri::AppHandle<R>) -> SqlResult<Self> {
        // Determine database path
        let data_dir = if let Some(dir) = dirs::data_dir() {
            dir.join("Canopy")
        } else {
            // Fallback to app data directory
            app_handle
                .path()
                .app_data_dir()
                .unwrap_or_else(|_| std::path::PathBuf::from("."))
        };

        // Create directory if it doesn't exist
        std::fs::create_dir_all(&data_dir).ok();

        let db_path = data_dir.join("canopy.db");
        let conn = Connection::open(&db_path)?;

        // Enable foreign keys
        conn.execute("PRAGMA foreign_keys = ON", [])?;

        let db = Database {
            conn: Mutex::new(conn),
        };

        // Run migrations
        db.run_migrations()?;

        tracing::info!("Database initialized at {:?}", db_path);
        Ok(db)
    }

    /// Initialize an in-memory database (primarily for testing)
    pub fn init_in_memory() -> SqlResult<Self> {
        let conn = Connection::open_in_memory()?;
        conn.execute("PRAGMA foreign_keys = ON", [])?;
        let db = Database {
            conn: Mutex::new(conn),
        };
        db.run_migrations()?;
        Ok(db)
    }

    /// Run all migrations to create tables
    fn run_migrations(&self) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        // Create agents table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS agents (
                id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                role TEXT NOT NULL,
                emoji TEXT NOT NULL,
                color TEXT NOT NULL,
                status TEXT NOT NULL,
                isolated BOOLEAN NOT NULL,
                container_id TEXT,
                personality_json TEXT NOT NULL,
                integrations_json TEXT NOT NULL,
                created_at TEXT NOT NULL,
                stats_json TEXT NOT NULL
            )",
            [],
        )?;

        // Migration: Add capabilities layer for Zero-Trust architecture
        let _ = conn.execute(
            "ALTER TABLE agents ADD COLUMN capabilities_json TEXT NOT NULL DEFAULT '{}'",
            [],
        );

        // Migration: Add memories feature
        let _ = conn.execute(
            "ALTER TABLE agents ADD COLUMN memories_json TEXT NOT NULL DEFAULT '[]'",
            [],
        );

        // Migration: Add visual identity
        let _ = conn.execute(
            "ALTER TABLE agents ADD COLUMN visual_identity_json TEXT NOT NULL DEFAULT '{}'",
            [],
        );

        // Migration: Add paused flag.
        // Paused agents are stored in SQLite but NOT registered with OpenClaw on boot.
        // This prevents their channels/sidecars from spawning processes, avoiding PID spirals
        // when multiple agents with heavy plugins (browser, voice, Slack) all initialize at once.
        let _ = conn.execute(
            "ALTER TABLE agents ADD COLUMN paused BOOLEAN NOT NULL DEFAULT 0",
            [],
        );

        // Create conversations table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS conversations (
                id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                title TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        // Create messages table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS messages (
                id TEXT PRIMARY KEY,
                conversation_id TEXT NOT NULL,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                FOREIGN KEY(conversation_id) REFERENCES conversations(id)
            )",
            [],
        )?;

        // Create bridges table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS bridges (
                id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                name TEXT NOT NULL,
                bridge_type TEXT NOT NULL,
                enabled BOOLEAN NOT NULL,
                config_json TEXT NOT NULL,
                permissions_json TEXT NOT NULL,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        // Create audit_log table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS audit_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                agent_id TEXT,
                action TEXT NOT NULL,
                bridge_type TEXT,
                detail TEXT NOT NULL,
                content_hash TEXT
            )",
            [],
        )?;

        // Create budgets table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS budgets (
                agent_id TEXT PRIMARY KEY,
                config_json TEXT NOT NULL,
                daily_spent_cents INTEGER NOT NULL DEFAULT 0,
                monthly_spent_cents INTEGER NOT NULL DEFAULT 0,
                last_reset_date TEXT NOT NULL,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        // Create purchase_history table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS purchase_history (
                id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                description TEXT NOT NULL,
                merchant TEXT NOT NULL,
                amount_cents INTEGER NOT NULL,
                category TEXT NOT NULL,
                decision TEXT NOT NULL,
                virtual_card_id TEXT,
                timestamp TEXT NOT NULL,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        // Create global_config table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS global_config (
                key TEXT PRIMARY KEY,
                value_json TEXT NOT NULL
            )",
            [],
        )?;

        // Create security_alerts table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS security_alerts (
                id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                severity TEXT NOT NULL,
                description TEXT NOT NULL,
                resolved BOOLEAN NOT NULL DEFAULT 0,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        // Create provider_models table for dynamic synchronization
        conn.execute(
            "CREATE TABLE IF NOT EXISTS provider_models (
                id TEXT PRIMARY KEY,
                provider TEXT NOT NULL,
                name TEXT NOT NULL,
                capabilities_json TEXT NOT NULL,
                recommended BOOLEAN NOT NULL,
                created_at TEXT NOT NULL
            )",
            [],
        )?;

        // Create voice_configs table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS voice_configs (
                agent_id TEXT PRIMARY KEY,
                config_json TEXT NOT NULL,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        // Create agent_bug_reports table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS agent_bug_reports (
                id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                service TEXT NOT NULL,
                error_message TEXT NOT NULL,
                resolved BOOLEAN NOT NULL DEFAULT 0,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        // Create inbox_items table
        conn.execute(
            "CREATE TABLE IF NOT EXISTS inbox_items (
                id TEXT PRIMARY KEY,
                item_type TEXT NOT NULL,
                status TEXT NOT NULL,
                payload_json TEXT NOT NULL,
                timestamp TEXT NOT NULL
            )",
            [],
        )?;

        // Create indexes for common queries

        let _ = conn.execute(
            "ALTER TABLE token_usage_history ADD COLUMN conversation_id TEXT",
            [],
        );

        conn.execute(
            "CREATE TABLE IF NOT EXISTS token_usage_history (
                id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                conversation_id TEXT,
                timestamp TEXT NOT NULL,
                model TEXT NOT NULL,
                provider TEXT NOT NULL,
                tokens_in INTEGER NOT NULL,
                tokens_out INTEGER NOT NULL,
                cost_usd REAL NOT NULL,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_token_usage_agent ON token_usage_history(agent_id)",
            [],
        )?;
        conn.execute("CREATE INDEX IF NOT EXISTS idx_token_usage_timestamp ON token_usage_history(timestamp)", [])?;

        conn.execute(
            "CREATE TABLE IF NOT EXISTS system_warnings (
                id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                warning_type TEXT NOT NULL,
                message TEXT NOT NULL,
                resolved INTEGER NOT NULL DEFAULT 0,
                FOREIGN KEY(agent_id) REFERENCES agents(id)
            )",
            [],
        )?;

        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_conversations_agent ON conversations(agent_id)",
            [],
        )?;
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id)",
            [],
        )?;
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_bridges_agent ON bridges(agent_id)",
            [],
        )?;
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_audit_log_agent ON audit_log(agent_id)",
            [],
        )?;
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log(timestamp)",
            [],
        )?;
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_purchase_history_agent ON purchase_history(agent_id)",
            [],
        )?;

        tracing::debug!("Database migrations completed");
        Ok(())
    }

    // ─── Global Config Operations ────────────────────────────────────────────

    pub fn get_user_profile(&self) -> SqlResult<UserProfile> {
        let conn = self.conn.lock().unwrap();
        let mut stmt =
            conn.prepare("SELECT value_json FROM global_config WHERE key = 'user_profile'")?;

        let json_str: String = match stmt.query_row([], |row| row.get(0)) {
            Ok(val) => val,
            Err(rusqlite::Error::QueryReturnedNoRows) => return Ok(UserProfile::default()),
            Err(e) => return Err(e),
        };

        let profile: UserProfile =
            serde_json::from_str(&json_str).unwrap_or_else(|_| UserProfile::default());
        Ok(profile)
    }

    pub fn save_user_profile(&self, profile: &UserProfile) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        let value_json = serde_json::to_string(profile).unwrap_or_else(|_| "{}".to_string());

        conn.execute(
            "INSERT INTO global_config (key, value_json) VALUES ('user_profile', ?1)
             ON CONFLICT(key) DO UPDATE SET value_json = excluded.value_json",
            params![value_json],
        )?;
        Ok(())
    }

    // ─── Inbox Operations ────────────────────────────────────────────────────

    pub fn get_inbox_items(&self) -> SqlResult<Vec<InboxItem>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, item_type, status, payload_json, timestamp FROM inbox_items ORDER BY timestamp DESC"
        )?;

        let items = stmt
            .query_map([], |row| {
                Ok(InboxItem {
                    id: row.get(0)?,
                    item_type: row.get(1)?,
                    status: row.get(2)?,
                    payload_json: row.get(3)?,
                    timestamp: row.get(4)?,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(items)
    }

    pub fn add_inbox_item(&self, item: &InboxItem) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO inbox_items (id, item_type, status, payload_json, timestamp)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![
                &item.id,
                &item.item_type,
                &item.status,
                &item.payload_json,
                &item.timestamp
            ],
        )?;
        Ok(())
    }

    pub fn update_inbox_item_status(&self, id: &str, status: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE inbox_items SET status = ?1 WHERE id = ?2",
            params![status, id],
        )?;
        Ok(())
    }

    pub fn delete_inbox_item(&self, id: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute("DELETE FROM inbox_items WHERE id = ?1", params![id])?;
        Ok(())
    }

    // ─── Agent CRUD Operations ───────────────────────────────────────────────

    /// Insert a new agent
    pub fn insert_agent(&self, agent: &Agent) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let personality_json =
            serde_json::to_string(&agent.personality).unwrap_or_else(|_| "{}".to_string());
        let capabilities_json =
            serde_json::to_string(&agent.capabilities).unwrap_or_else(|_| "{}".to_string());
        let integrations_json =
            serde_json::to_string(&agent.integrations).unwrap_or_else(|_| "[]".to_string());
        let stats_json = serde_json::to_string(&agent.stats).unwrap_or_else(|_| "{}".to_string());
        let status_str = status_to_string(&agent.status);

        let memories_json =
            serde_json::to_string(&agent.memories).unwrap_or_else(|_| "[]".to_string());
        let vi_json =
            serde_json::to_string(&agent.visual_identity).unwrap_or_else(|_| "{}".to_string());

        conn.execute(
            "INSERT INTO agents
                (id, name, role, emoji, color, status, isolated, container_id,
                 personality_json, capabilities_json, integrations_json, created_at, stats_json, memories_json, visual_identity_json)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15)",
            params![
                &agent.id,
                &agent.name,
                &agent.role,
                &agent.emoji,
                &agent.color,
                status_str,
                agent.isolated,
                &agent.container_id,
                personality_json,
                capabilities_json,
                integrations_json,
                agent.created_at.to_rfc3339(),
                stats_json,
                memories_json,
                vi_json,
            ],
        )?;

        Ok(())
    }

    /// Get an agent by ID
    pub fn get_agent(&self, id: &str) -> SqlResult<Option<Agent>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT id, name, role, emoji, color, status, isolated, container_id,
                    personality_json, capabilities_json, integrations_json, created_at, stats_json, memories_json, visual_identity_json, paused
             FROM agents WHERE id = ?1",
        )?;

        let agent = stmt
            .query_row(params![id], |row| {
                let status_str: String = row.get(5)?;
                let personality_json: String = row.get(8)?;
                let capabilities_json: String = row.get(9)?;
                let integrations_json: String = row.get(10)?;
                let stats_json: String = row.get(12)?;
                let created_at_str: String = row.get(11)?;
                let memories_json: String = row.get(13).unwrap_or_else(|_| "[]".to_string());
                let vi_json: String = row.get(14).unwrap_or_else(|_| "{}".to_string());
                let paused: bool = row.get(15).unwrap_or(false);

                Ok(Agent {
                    id: row.get(0)?,
                    name: row.get(1)?,
                    role: row.get(2)?,
                    emoji: row.get(3)?,
                    color: row.get(4)?,
                    status: string_to_status(&status_str),
                    isolated: row.get(6)?,
                    paused,
                    container_id: row.get(7)?,
                    personality: serde_json::from_str(&personality_json).unwrap_or_default(),
                    capabilities: serde_json::from_str(&capabilities_json).unwrap_or_default(),
                    integrations: serde_json::from_str(&integrations_json).unwrap_or_default(),
                    memories: serde_json::from_str(&memories_json).unwrap_or_default(),
                    created_at: chrono::DateTime::parse_from_rfc3339(&created_at_str)
                        .unwrap_or_else(|_| chrono::DateTime::default())
                        .with_timezone(&Utc),
                    stats: serde_json::from_str(&stats_json).unwrap_or_default(),
                    visual_identity: serde_json::from_str(&vi_json).ok(),
                })
            })
            .optional()?;

        Ok(agent)
    }

    /// List all agents
    pub fn list_agents(&self) -> SqlResult<Vec<Agent>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT id, name, role, emoji, color, status, isolated, container_id,
                    personality_json, capabilities_json, integrations_json, created_at, stats_json, memories_json, visual_identity_json, paused
             FROM agents ORDER BY created_at DESC",
        )?;

        let agents = stmt
            .query_map([], |row| {
                let status_str: String = row.get(5)?;
                let personality_json: String = row.get(8)?;
                let capabilities_json: String = row.get(9)?;
                let integrations_json: String = row.get(10)?;
                let stats_json: String = row.get(12)?;
                let created_at_str: String = row.get(11)?;
                let memories_json: String = row.get(13).unwrap_or_else(|_| "[]".to_string());
                let vi_json: String = row.get(14).unwrap_or_else(|_| "{}".to_string());
                let paused: bool = row.get(15).unwrap_or(false);

                Ok(Agent {
                    id: row.get(0)?,
                    name: row.get(1)?,
                    role: row.get(2)?,
                    emoji: row.get(3)?,
                    color: row.get(4)?,
                    status: string_to_status(&status_str),
                    isolated: row.get(6)?,
                    paused,
                    container_id: row.get(7)?,
                    personality: serde_json::from_str(&personality_json).unwrap_or_default(),
                    capabilities: serde_json::from_str(&capabilities_json).unwrap_or_default(),
                    integrations: serde_json::from_str(&integrations_json).unwrap_or_default(),
                    memories: serde_json::from_str(&memories_json).unwrap_or_default(),
                    created_at: chrono::DateTime::parse_from_rfc3339(&created_at_str)
                        .unwrap_or_else(|_| chrono::DateTime::default())
                        .with_timezone(&Utc),
                    stats: serde_json::from_str(&stats_json).unwrap_or_default(),
                    visual_identity: serde_json::from_str(&vi_json).ok(),
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(agents)
    }

    /// Set paused state for an agent
    pub fn set_agent_paused(&self, id: &str, paused: bool) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE agents SET paused = ?1 WHERE id = ?2",
            params![paused, id],
        )?;
        Ok(())
    }

    /// Update an existing agent
    pub fn update_agent(&self, agent: &Agent) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let personality_json =
            serde_json::to_string(&agent.personality).unwrap_or_else(|_| "{}".to_string());
        let capabilities_json =
            serde_json::to_string(&agent.capabilities).unwrap_or_else(|_| "{}".to_string());
        let integrations_json =
            serde_json::to_string(&agent.integrations).unwrap_or_else(|_| "[]".to_string());
        let stats_json = serde_json::to_string(&agent.stats).unwrap_or_else(|_| "{}".to_string());
        let memories_json =
            serde_json::to_string(&agent.memories).unwrap_or_else(|_| "[]".to_string());
        let vi_json =
            serde_json::to_string(&agent.visual_identity).unwrap_or_else(|_| "{}".to_string());
        let status_str = status_to_string(&agent.status);

        conn.execute(
            "UPDATE agents
             SET name = ?1, role = ?2, emoji = ?3, color = ?4, status = ?5,
                 isolated = ?6, container_id = ?7, personality_json = ?8,
                 capabilities_json = ?9, integrations_json = ?10, stats_json = ?11, memories_json = ?12, visual_identity_json = ?13,
                 paused = ?14
             WHERE id = ?15",
            params![
                &agent.name,
                &agent.role,
                &agent.emoji,
                &agent.color,
                status_str,
                agent.isolated,
                &agent.container_id,
                personality_json,
                capabilities_json,
                integrations_json,
                stats_json,
                memories_json,
                vi_json,
                agent.paused,
                &agent.id,
            ],
        )?;

        Ok(())
    }

    /// Delete an agent
    pub fn delete_agent(&self, id: &str) -> SqlResult<()> {
        let mut conn = self.conn.lock().unwrap();
        let tx = conn.transaction()?;

        // Clean up all child relational tables to avoid FOREIGN KEY constraints
        tx.execute("DELETE FROM messages WHERE conversation_id IN (SELECT id FROM conversations WHERE agent_id = ?1)", params![id])?;
        tx.execute("DELETE FROM conversations WHERE agent_id = ?1", params![id])?;
        tx.execute("DELETE FROM bridges WHERE agent_id = ?1", params![id])?;
        tx.execute("DELETE FROM budgets WHERE agent_id = ?1", params![id])?;
        tx.execute(
            "DELETE FROM purchase_history WHERE agent_id = ?1",
            params![id],
        )?;
        tx.execute("DELETE FROM audit_log WHERE agent_id = ?1", params![id])?;
        tx.execute(
            "DELETE FROM security_alerts WHERE agent_id = ?1",
            params![id],
        )?;
        tx.execute("DELETE FROM voice_configs WHERE agent_id = ?1", params![id])?;
        tx.execute(
            "DELETE FROM agent_bug_reports WHERE agent_id = ?1",
            params![id],
        )?;

        // Finally delete the main agent record
        tx.execute("DELETE FROM agents WHERE id = ?1", params![id])?;

        tx.commit()?;
        Ok(())
    }

    // ─── Authorization & Permission Checks ──────────────────────────────────

    /// Check if a user owns an agent
    /// For now, returns true if agent exists (single-user mode)
    /// TODO: Implement multi-user support with user_id foreign key in agents table
    pub fn is_agent_owner(&self, agent_id: &str, _user_id: &str) -> SqlResult<bool> {
        let conn = self.conn.lock().unwrap();

        let exists: bool = conn
            .query_row(
                "SELECT 1 FROM agents WHERE id = ?1 LIMIT 1",
                params![agent_id],
                |_| Ok(true),
            )
            .optional()?
            .unwrap_or(false);

        Ok(exists)
    }

    /// Check if a user owns a budget
    /// For now, returns true if budget exists for the agent
    pub fn is_budget_owner(&self, agent_id: &str, _user_id: &str) -> SqlResult<bool> {
        let conn = self.conn.lock().unwrap();

        let exists: bool = conn
            .query_row(
                "SELECT 1 FROM budgets WHERE agent_id = ?1 LIMIT 1",
                params![agent_id],
                |_| Ok(true),
            )
            .optional()?
            .unwrap_or(false);

        Ok(exists)
    }

    /// Check if a user owns a conversation
    /// For now, returns true if conversation exists for the agent
    pub fn is_conversation_owner(&self, conversation_id: &str, _user_id: &str) -> SqlResult<bool> {
        let conn = self.conn.lock().unwrap();

        let exists: bool = conn
            .query_row(
                "SELECT 1 FROM conversations WHERE id = ?1 LIMIT 1",
                params![conversation_id],
                |_| Ok(true),
            )
            .optional()?
            .unwrap_or(false);

        Ok(exists)
    }

    /// Check if a user has permission to modify an agent
    /// Combines existence check with future permission system
    pub fn can_modify_agent(&self, agent_id: &str, user_id: &str) -> SqlResult<bool> {
        self.is_agent_owner(agent_id, user_id)
    }

    /// Check if a user has permission to delete an agent
    pub fn can_delete_agent(&self, agent_id: &str, user_id: &str) -> SqlResult<bool> {
        self.is_agent_owner(agent_id, user_id)
    }

    // ─── Conversation & Message Operations ──────────────────────────────────

    /// Ensure a specific conversation ID exists for an agent
    pub fn ensure_conversation(&self, conv_id: &str, agent_id: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        // Check if exists
        let mut stmt = conn.prepare("SELECT 1 FROM conversations WHERE id = ?1")?;
        if stmt
            .query_row(params![conv_id], |_| Ok(()))
            .optional()?
            .is_some()
        {
            return Ok(());
        }

        // Create
        let now = Utc::now().to_rfc3339();
        conn.execute(
            "INSERT INTO conversations (id, agent_id, title, created_at, updated_at)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![conv_id, agent_id, "New Conversation", &now, &now],
        )?;

        Ok(())
    }

    /// Get or create a conversation for an agent
    pub fn get_or_create_conversation(&self, agent_id: &str) -> SqlResult<String> {
        let conn = self.conn.lock().unwrap();

        // Check if a conversation already exists for this agent
        let mut stmt = conn.prepare(
            "SELECT id FROM conversations WHERE agent_id = ?1 ORDER BY created_at DESC LIMIT 1",
        )?;

        if let Some(existing_id) = stmt
            .query_row(params![agent_id], |row| row.get::<_, String>(0))
            .optional()?
        {
            return Ok(existing_id);
        }

        // Create a new conversation
        let conv_id = Uuid::new_v4().to_string();
        let now = Utc::now().to_rfc3339();

        conn.execute(
            "INSERT INTO conversations (id, agent_id, title, created_at, updated_at)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![
                &conv_id,
                agent_id,
                format!("Conversation with {}", agent_id),
                &now,
                &now,
            ],
        )?;

        Ok(conv_id)
    }

    /// Insert a message into a conversation
    pub fn insert_message(&self, conv_id: &str, role: &str, content: &str) -> SqlResult<String> {
        let conn = self.conn.lock().unwrap();

        let msg_id = Uuid::new_v4().to_string();
        let timestamp = Utc::now().to_rfc3339();

        conn.execute(
            "INSERT INTO messages (id, conversation_id, role, content, timestamp)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![&msg_id, conv_id, role, content, &timestamp,],
        )?;

        // Update conversation's updated_at timestamp
        conn.execute(
            "UPDATE conversations SET updated_at = ?1 WHERE id = ?2",
            params![&timestamp, conv_id],
        )?;

        Ok(msg_id)
    }

    /// Get messages from a conversation with limit
    pub fn get_messages(&self, conv_id: &str, limit: u32) -> SqlResult<Vec<Message>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT id, conversation_id, role, content, timestamp
             FROM messages
             WHERE conversation_id = ?1
             ORDER BY timestamp DESC
             LIMIT ?2",
        )?;

        let messages = stmt
            .query_map(params![conv_id, limit as i32], |row| {
                Ok(Message {
                    id: row.get(0)?,
                    conversation_id: row.get(1)?,
                    role: row.get(2)?,
                    content: row.get(3)?,
                    timestamp: row.get(4)?,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        // Reverse to get oldest first
        Ok(messages.into_iter().rev().collect())
    }

    /// List durable conversation summaries for an agent, newest activity first.
    pub fn list_agent_conversation_summaries(
        &self,
        agent_id: &str,
        limit: u32,
    ) -> SqlResult<Vec<ConversationSummary>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT
                c.id,
                c.agent_id,
                c.title,
                c.created_at,
                c.updated_at,
                COUNT(m.id) AS message_count,
                (
                    SELECT content
                    FROM messages fm
                    WHERE fm.conversation_id = c.id
                      AND fm.role = 'user'
                    ORDER BY fm.timestamp ASC
                    LIMIT 1
                ) AS first_user_message
             FROM conversations c
             LEFT JOIN messages m ON m.conversation_id = c.id
             WHERE c.agent_id = ?1
             GROUP BY c.id, c.agent_id, c.title, c.created_at, c.updated_at
             ORDER BY c.updated_at DESC
             LIMIT ?2",
        )?;

        let rows = stmt.query_map(params![agent_id, limit as i32], |row| {
            Ok(ConversationSummary {
                id: row.get(0)?,
                agent_id: row.get(1)?,
                title: row.get(2)?,
                created_at: row.get(3)?,
                updated_at: row.get(4)?,
                message_count: row.get::<_, i64>(5)?.max(0) as u32,
                first_user_message: row.get(6)?,
            })
        })?;

        rows.collect::<SqlResult<Vec<_>>>()
    }

    // ─── Bridge Operations ──────────────────────────────────────────────────

    /// Insert a new bridge
    pub fn insert_bridge(&self, bridge: &Bridge) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let bridge_type_str =
            serde_json::to_string(&bridge.bridge_type).unwrap_or_else(|_| "custom".to_string());
        let config_json =
            serde_json::to_string(&bridge.config).unwrap_or_else(|_| "{}".to_string());
        let permissions_json =
            serde_json::to_string(&bridge.permissions).unwrap_or_else(|_| "{}".to_string());

        conn.execute(
            "INSERT INTO bridges
                (id, agent_id, name, bridge_type, enabled, config_json, permissions_json)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
            params![
                &bridge.id,
                &bridge.agent_id,
                &bridge.name,
                bridge_type_str,
                bridge.enabled,
                config_json,
                permissions_json,
            ],
        )?;

        Ok(())
    }

    /// Get a bridge by ID
    pub fn get_bridge(&self, id: &str) -> SqlResult<Option<Bridge>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT id, agent_id, name, bridge_type, enabled, config_json, permissions_json
             FROM bridges WHERE id = ?1",
        )?;

        let bridge = stmt
            .query_row(params![id], |row| {
                let bridge_type_str: String = row.get(3)?;
                let config_json: String = row.get(5)?;
                let permissions_json: String = row.get(6)?;

                Ok(Bridge {
                    id: row.get(0)?,
                    agent_id: row.get(1)?,
                    name: row.get(2)?,
                    bridge_type: serde_json::from_str(&bridge_type_str)
                        .unwrap_or(BridgeType::Custom),
                    enabled: row.get(4)?,
                    config: serde_json::from_str(&config_json).unwrap_or_default(),
                    permissions: serde_json::from_str(&permissions_json).unwrap_or_default(),
                })
            })
            .optional()?;

        Ok(bridge)
    }

    /// List bridges for an agent
    pub fn list_bridges(&self, agent_id: &str) -> SqlResult<Vec<Bridge>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT id, agent_id, name, bridge_type, enabled, config_json, permissions_json
             FROM bridges WHERE agent_id = ?1",
        )?;

        let bridges = stmt
            .query_map(params![agent_id], |row| {
                let bridge_type_str: String = row.get(3)?;
                let config_json: String = row.get(5)?;
                let permissions_json: String = row.get(6)?;

                Ok(Bridge {
                    id: row.get(0)?,
                    agent_id: row.get(1)?,
                    name: row.get(2)?,
                    bridge_type: serde_json::from_str(&bridge_type_str)
                        .unwrap_or(BridgeType::Custom),
                    enabled: row.get(4)?,
                    config: serde_json::from_str(&config_json).unwrap_or_default(),
                    permissions: serde_json::from_str(&permissions_json).unwrap_or_default(),
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(bridges)
    }

    /// List all bridges globally across the platform
    pub fn list_all_bridges(&self) -> SqlResult<Vec<Bridge>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT id, agent_id, name, bridge_type, enabled, config_json, permissions_json
             FROM bridges",
        )?;

        let bridges = stmt
            .query_map([], |row| {
                let bridge_type_str: String = row.get(3)?;
                let config_json: String = row.get(5)?;
                let permissions_json: String = row.get(6)?;

                Ok(Bridge {
                    id: row.get(0)?,
                    agent_id: row.get(1)?,
                    name: row.get(2)?,
                    bridge_type: serde_json::from_str(&bridge_type_str)
                        .unwrap_or(BridgeType::Custom),
                    enabled: row.get(4)?,
                    config: serde_json::from_str(&config_json).unwrap_or_default(),
                    permissions: serde_json::from_str(&permissions_json).unwrap_or_default(),
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(bridges)
    }

    /// Update a bridge
    pub fn update_bridge(&self, bridge: &Bridge) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let bridge_type_str =
            serde_json::to_string(&bridge.bridge_type).unwrap_or_else(|_| "custom".to_string());
        let config_json =
            serde_json::to_string(&bridge.config).unwrap_or_else(|_| "{}".to_string());
        let permissions_json =
            serde_json::to_string(&bridge.permissions).unwrap_or_else(|_| "{}".to_string());

        conn.execute(
            "UPDATE bridges
             SET name = ?1, bridge_type = ?2, enabled = ?3, config_json = ?4, permissions_json = ?5
             WHERE id = ?6",
            params![
                &bridge.name,
                bridge_type_str,
                bridge.enabled,
                config_json,
                permissions_json,
                &bridge.id,
            ],
        )?;

        Ok(())
    }

    /// Delete a bridge
    pub fn delete_bridge(&self, id: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        conn.execute("DELETE FROM bridges WHERE id = ?1", params![id])?;

        Ok(())
    }

    // ─── Audit Log Operations ──────────────────────────────────────────────

    /// Log an audit entry
    pub fn log_audit(
        &self,
        agent_id: &str,
        action: &str,
        bridge_type: Option<&str>,
        detail: &str,
        content_hash: Option<&str>,
    ) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let timestamp = Utc::now().to_rfc3339();

        conn.execute(
            "INSERT INTO audit_log
                (timestamp, agent_id, action, bridge_type, detail, content_hash)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                &timestamp,
                agent_id,
                action,
                bridge_type,
                detail,
                content_hash,
            ],
        )?;

        Ok(())
    }

    // ─── Security Alerts Operations ──────────────────────────────────────────

    pub fn insert_security_alert(&self, alert: &SecurityAlert) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO security_alerts (id, agent_id, timestamp, severity, description, resolved)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                &alert.id,
                &alert.agent_id,
                &alert.timestamp,
                &alert.severity,
                &alert.description,
                alert.resolved
            ],
        )?;
        Ok(())
    }

    pub fn get_active_security_alerts(&self) -> SqlResult<Vec<SecurityAlert>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, agent_id, timestamp, severity, description, resolved 
             FROM security_alerts 
             WHERE resolved = 0 
             ORDER BY timestamp DESC",
        )?;

        let alerts = stmt
            .query_map([], |row| {
                Ok(SecurityAlert {
                    id: row.get(0)?,
                    agent_id: row.get(1)?,
                    timestamp: row.get(2)?,
                    severity: row.get(3)?,
                    description: row.get(4)?,
                    resolved: row.get(5)?,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(alerts)
    }

    pub fn resolve_security_alert(&self, alert_id: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE security_alerts SET resolved = 1 WHERE id = ?1",
            params![alert_id],
        )?;
        Ok(())
    }

    // ─── Self-Healing Agent Operations ───────────────────────────────────────

    pub fn insert_agent_bug_report(&self, report: &AgentBugReport) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO agent_bug_reports (id, agent_id, timestamp, service, error_message, resolved)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                &report.id,
                &report.agent_id,
                &report.timestamp,
                &report.service,
                &report.error_message,
                report.resolved
            ],
        )?;
        Ok(())
    }

    pub fn get_unresolved_bug_reports(&self) -> SqlResult<Vec<AgentBugReport>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, agent_id, timestamp, service, error_message, resolved
             FROM agent_bug_reports
             WHERE resolved = 0
             ORDER BY timestamp DESC",
        )?;

        let reports = stmt
            .query_map([], |row| {
                Ok(AgentBugReport {
                    id: row.get(0)?,
                    agent_id: row.get(1)?,
                    timestamp: row.get(2)?,
                    service: row.get(3)?,
                    error_message: row.get(4)?,
                    resolved: row.get(5)?,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(reports)
    }

    pub fn resolve_bug_report(&self, report_id: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE agent_bug_reports SET resolved = 1 WHERE id = ?1",
            params![report_id],
        )?;
        Ok(())
    }

    /// Get audit log entries
    pub fn get_audit_log(&self, agent_id: Option<&str>, limit: u32) -> SqlResult<Vec<AuditEntry>> {
        let conn = self.conn.lock().unwrap();

        let (query, params_vec): (String, Vec<Box<dyn rusqlite::ToSql>>) = if let Some(agent_id) =
            agent_id
        {
            (
                "SELECT id, timestamp, agent_id, action, bridge_type, detail, content_hash
                 FROM (
                     SELECT id, timestamp, agent_id, action, bridge_type, detail, content_hash
                     FROM audit_log
                     UNION ALL
                     SELECT (m.rowid + 10000000) as id, m.timestamp, c.agent_id, 'chatted' as action, 
                            CASE WHEN m.role = 'user' THEN 'user' ELSE 'app' END as bridge_type, 
                            substr(m.content, 1, 150) as detail, NULL as content_hash
                     FROM messages m
                     JOIN conversations c ON m.conversation_id = c.id
                 )
                 WHERE agent_id = ?1
                 ORDER BY timestamp DESC
                 LIMIT ?2".to_string(),
                vec![Box::new(agent_id.to_string()), Box::new(limit as i32)],
            )
        } else {
            (
                "SELECT id, timestamp, agent_id, action, bridge_type, detail, content_hash
                 FROM (
                     SELECT id, timestamp, agent_id, action, bridge_type, detail, content_hash
                     FROM audit_log
                     UNION ALL
                     SELECT (m.rowid + 10000000) as id, m.timestamp, c.agent_id, 'chatted' as action, 
                            CASE WHEN m.role = 'user' THEN 'user' ELSE 'app' END as bridge_type, 
                            substr(m.content, 1, 150) as detail, NULL as content_hash
                     FROM messages m
                     JOIN conversations c ON m.conversation_id = c.id
                 )
                 ORDER BY timestamp DESC
                 LIMIT ?1".to_string(),
                vec![Box::new(limit as i32)],
            )
        };

        let mut stmt = conn.prepare(&query)?;

        let entries = if agent_id.is_some() {
            stmt.query_map(params![agent_id, limit as i32], |row| {
                Ok(AuditEntry {
                    id: row.get(0)?,
                    timestamp: row.get(1)?,
                    agent_id: row.get(2)?,
                    action: row.get(3)?,
                    bridge_type: row.get(4)?,
                    detail: row.get(5)?,
                    content_hash: row.get(6)?,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?
        } else {
            stmt.query_map(params![limit as i32], |row| {
                Ok(AuditEntry {
                    id: row.get(0)?,
                    timestamp: row.get(1)?,
                    agent_id: row.get(2)?,
                    action: row.get(3)?,
                    bridge_type: row.get(4)?,
                    detail: row.get(5)?,
                    content_hash: row.get(6)?,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?
        };

        Ok(entries)
    }

    pub fn get_agent_browser_history(
        &self,
        agent_id: &str,
        limit: u32,
    ) -> SqlResult<Vec<BrowserHistoryEntry>> {
        let conn = self.conn.lock().unwrap();

        let query = "
            SELECT timestamp, action, detail 
            FROM audit_log 
            WHERE agent_id = ?1 AND detail LIKE '%http%'
            ORDER BY timestamp DESC
            LIMIT ?2
        ";

        let mut stmt = conn.prepare(query)?;

        let entries = stmt
            .query_map(params![agent_id, limit], |row| {
                Ok(BrowserHistoryEntry {
                    timestamp: row.get(0)?,
                    action: row.get(1)?,
                    detail: row.get(2)?,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(entries)
    }

    /// Get aggregated daily activity counts for the last 90 days
    pub fn get_agent_activity_heatmap(
        &self,
        agent_id: &str,
    ) -> SqlResult<Vec<ActivityHeatmapEntry>> {
        let conn = self.conn.lock().unwrap();

        let query = "
            WITH RECURSIVE dates(date) AS (
                SELECT date('now', '-89 days')
                UNION ALL
                SELECT date(date, '+1 day')
                FROM dates
                WHERE date < date('now')
            ),
            combined_logs AS (
                SELECT date(timestamp) as log_date, action, bridge_type
                FROM audit_log
                WHERE agent_id = ?1 AND timestamp >= datetime('now', '-90 days')
                
                UNION ALL
                
                SELECT date(m.timestamp) as log_date, 'chatted' as action, 
                       CASE WHEN m.role = 'user' THEN 'user' ELSE 'app' END as bridge_type
                FROM messages m
                JOIN conversations c ON m.conversation_id = c.id
                WHERE c.agent_id = ?1 AND m.timestamp >= datetime('now', '-90 days')
            )
            SELECT 
                d.date,
                SUM(CASE WHEN c.action = 'chatted' THEN 1 ELSE 0 END) as interactions,
                SUM(CASE WHEN c.action = 'tool_call' OR (c.action != 'chatted' AND c.bridge_type IS NOT NULL) THEN 1 ELSE 0 END) as tools,
                SUM(CASE WHEN c.action != 'chatted' AND c.action != 'tool_call' AND c.bridge_type IS NULL THEN 1 ELSE 0 END) as system
            FROM dates d
            LEFT JOIN combined_logs c ON d.date = c.log_date
            GROUP BY d.date
            ORDER BY d.date ASC
        ";

        let mut stmt = conn.prepare(query)?;

        let heatmap = stmt
            .query_map(params![agent_id], |row| {
                let interactions: u32 = row.get(1).unwrap_or(0);
                let tools: u32 = row.get(2).unwrap_or(0);
                let system: u32 = row.get(3).unwrap_or(0);

                Ok(ActivityHeatmapEntry {
                    date: row.get(0)?,
                    interactions,
                    tools,
                    system,
                    total: interactions + tools + system,
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(heatmap)
    }

    // ─── Budget Operations ─────────────────────────────────────────────────

    /// Get a budget for an agent
    pub fn get_budget(&self, agent_id: &str) -> SqlResult<Option<AgentBudget>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT agent_id, config_json, daily_spent_cents, monthly_spent_cents, last_reset_date
             FROM budgets WHERE agent_id = ?1",
        )?;

        let budget = stmt
            .query_row(params![agent_id], |row| {
                let config_json: String = row.get(1)?;
                let default_budget = AgentBudget {
                    agent_id: row.get(0)?,
                    payments_enabled: false,
                    auto_approve_threshold_cents: 0,
                    per_transaction_limit_cents: 0,
                    daily_limit_cents: 0,
                    monthly_limit_cents: 0,
                    allowed_categories: vec![],
                    daily_spent_cents: row.get(2)?,
                    monthly_spent_cents: row.get(3)?,
                    require_approval_new_merchant: false,
                    require_approval_recurring: false,
                };

                let mut config: AgentBudget =
                    serde_json::from_str(&config_json).unwrap_or(default_budget);
                config.daily_spent_cents = row.get(2)?;
                config.monthly_spent_cents = row.get(3)?;

                Ok(config)
            })
            .optional()?;

        Ok(budget)
    }

    /// Insert or update a budget
    pub fn upsert_budget(&self, budget: &AgentBudget) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let config_json = serde_json::to_string(budget).unwrap_or_else(|_| "{}".to_string());
        let last_reset = Utc::now().to_rfc3339();

        conn.execute(
            "INSERT OR REPLACE INTO budgets
                (agent_id, config_json, daily_spent_cents, monthly_spent_cents, last_reset_date)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![
                &budget.agent_id,
                config_json,
                budget.daily_spent_cents,
                budget.monthly_spent_cents,
                &last_reset,
            ],
        )?;

        Ok(())
    }

    /// Record a purchase
    pub fn record_purchase(&self, record: &PurchaseRecord) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let decision_json =
            serde_json::to_string(&record.decision).unwrap_or_else(|_| "{}".to_string());

        conn.execute(
            "INSERT INTO purchase_history
                (id, agent_id, description, merchant, amount_cents, category, decision, virtual_card_id, timestamp)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
            params![
                &record.id,
                &record.agent_id,
                &record.description,
                &record.merchant,
                record.amount_cents as i32,
                &record.category,
                decision_json,
                &record.virtual_card_id,
                record.timestamp.to_rfc3339(),
            ],
        )?;

        Ok(())
    }

    /// Get purchase history for an agent
    pub fn get_purchase_history(
        &self,
        agent_id: &str,
        limit: u32,
    ) -> SqlResult<Vec<PurchaseRecord>> {
        let conn = self.conn.lock().unwrap();

        let mut stmt = conn.prepare(
            "SELECT id, agent_id, description, merchant, amount_cents, category, decision, virtual_card_id, timestamp
             FROM purchase_history
             WHERE agent_id = ?1
             ORDER BY timestamp DESC
             LIMIT ?2",
        )?;

        let records = stmt
            .query_map(params![agent_id, limit as i32], |row| {
                let decision_json: String = row.get(6)?;
                let timestamp_str: String = row.get(8)?;

                Ok(PurchaseRecord {
                    id: row.get(0)?,
                    agent_id: row.get(1)?,
                    description: row.get(2)?,
                    merchant: row.get(3)?,
                    amount_cents: row.get::<_, i32>(4)? as u64,
                    category: row.get(5)?,
                    decision: serde_json::from_str(&decision_json).unwrap_or(
                        PurchaseDecision::Denied {
                            reasons: vec!["Failed to deserialize decision".to_string()],
                        },
                    ),
                    virtual_card_id: row.get(7)?,
                    timestamp: chrono::DateTime::parse_from_rfc3339(&timestamp_str)
                        .unwrap_or_else(|_| chrono::DateTime::default())
                        .with_timezone(&Utc),
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(records)
    }

    // ─── Budget Reset Operations ───────────────────────────────────────────

    /// Reset daily budgets for all agents (call on daily schedule)
    pub fn reset_daily_budgets(&self) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let now = Utc::now().to_rfc3339();

        conn.execute(
            "UPDATE budgets SET daily_spent_cents = 0, last_reset_date = ?1",
            params![&now],
        )?;

        self.log_audit_internal(
            &conn,
            None,
            "reset_daily_budgets",
            None,
            "Daily budgets reset",
            None,
        )?;

        Ok(())
    }

    /// Reset monthly budgets for all agents (call on monthly schedule)
    pub fn reset_monthly_budgets(&self) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        let now = Utc::now().to_rfc3339();

        conn.execute(
            "UPDATE budgets SET monthly_spent_cents = 0, last_reset_date = ?1",
            params![&now],
        )?;

        self.log_audit_internal(
            &conn,
            None,
            "reset_monthly_budgets",
            None,
            "Monthly budgets reset",
            None,
        )?;

        Ok(())
    }

    // ─── Utility ─────────────────────────────────────────────────────────────

    /// Internal audit logging (used without needing to re-lock the mutex)
    fn log_audit_internal(
        &self,
        conn: &Connection,
        agent_id: Option<&str>,
        action: &str,
        bridge_type: Option<&str>,
        detail: &str,
        content_hash: Option<&str>,
    ) -> SqlResult<()> {
        let timestamp = Utc::now().to_rfc3339();

        conn.execute(
            "INSERT INTO audit_log
                (timestamp, agent_id, action, bridge_type, detail, content_hash)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                &timestamp,
                agent_id,
                action,
                bridge_type,
                detail,
                content_hash,
            ],
        )?;

        Ok(())
    }

    /// Update agent spending (called after successful purchase)
    pub fn update_agent_spending(
        &self,
        agent_id: &str,
        amount_cents: u64,
        is_daily: bool,
        is_monthly: bool,
    ) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        if is_daily {
            conn.execute(
                "UPDATE budgets SET daily_spent_cents = daily_spent_cents + ?1 WHERE agent_id = ?2",
                params![amount_cents as i32, agent_id],
            )?;
        }

        if is_monthly {
            conn.execute(
                "UPDATE budgets SET monthly_spent_cents = monthly_spent_cents + ?1 WHERE agent_id = ?2",
                params![amount_cents as i32, agent_id],
            )?;
        }

        Ok(())
    }

    /// Delete all data for testing/reset purposes
    #[cfg(test)]
    pub fn clear_all(&self) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();

        conn.execute("DELETE FROM purchase_history", [])?;
        conn.execute("DELETE FROM budgets", [])?;
        conn.execute("DELETE FROM audit_log", [])?;
        conn.execute("DELETE FROM bridges", [])?;
        conn.execute("DELETE FROM messages", [])?;
        conn.execute("DELETE FROM conversations", [])?;
        conn.execute("DELETE FROM agents", [])?;

        Ok(())
    }

    // ─── Provider Models Operations ──────────────────────────────────────────

    pub fn insert_provider_models(&self, models: Vec<ProviderModel>) -> SqlResult<()> {
        let mut conn = self.conn.lock().unwrap();
        let tx = conn.transaction()?;

        // To keep logic simple, we can upsert
        for m in models {
            let caps_json =
                serde_json::to_string(&m.capabilities).unwrap_or_else(|_| "[]".to_string());
            tx.execute(
                "INSERT INTO provider_models (id, provider, name, capabilities_json, recommended, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                 ON CONFLICT(id) DO UPDATE SET 
                    name = excluded.name,
                    capabilities_json = excluded.capabilities_json,
                    recommended = CASE WHEN recommended = 1 THEN excluded.recommended ELSE recommended END",
                params![&m.id, &m.provider, &m.name, &caps_json, &m.recommended, m.created_at.to_rfc3339()],
            )?;
        }

        tx.commit()?;
        Ok(())
    }

    pub fn get_provider_models(&self) -> SqlResult<Vec<ProviderModel>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, provider, name, capabilities_json, recommended, created_at FROM provider_models ORDER BY provider ASC, id DESC"
        )?;

        let models = stmt
            .query_map([], |row| {
                let caps_json: String = row.get(3)?;
                let created_at_str: String = row.get(5)?;
                Ok(ProviderModel {
                    id: row.get(0)?,
                    provider: row.get(1)?,
                    name: row.get(2)?,
                    capabilities: serde_json::from_str(&caps_json).unwrap_or_default(),
                    recommended: row.get(4)?,
                    created_at: chrono::DateTime::parse_from_rfc3339(&created_at_str)
                        .unwrap_or_else(|_| chrono::DateTime::default())
                        .with_timezone(&Utc),
                })
            })?
            .collect::<SqlResult<Vec<_>>>()?;

        Ok(models)
    }

    pub fn remove_provider_model(&self, id: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute("DELETE FROM provider_models WHERE id = ?1", params![id])?;
        Ok(())
    }

    // ─── Voice Operations ────────────────────────────────────────────────────

    pub fn upsert_voice_config(&self, config: &crate::voice::VoiceConfig) -> Result<(), String> {
        let conn = self.conn.lock().unwrap();
        let config_json = config.to_json().map_err(|e| e.to_string())?;

        conn.execute(
            "INSERT INTO voice_configs (agent_id, config_json) VALUES (?1, ?2)
             ON CONFLICT(agent_id) DO UPDATE SET config_json = excluded.config_json",
            params![&config.agent_id, config_json],
        )
        .map_err(|e| e.to_string())?;

        Ok(())
    }

    pub fn get_voice_config(
        &self,
        agent_id: &str,
    ) -> Result<Option<crate::voice::VoiceConfig>, String> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn
            .prepare("SELECT config_json FROM voice_configs WHERE agent_id = ?1")
            .map_err(|e| e.to_string())?;

        let json_str: String = match stmt.query_row(params![agent_id], |row| row.get(0)) {
            Ok(val) => val,
            Err(rusqlite::Error::QueryReturnedNoRows) => return Ok(None),
            Err(e) => return Err(e.to_string()),
        };

        let config = crate::voice::VoiceConfig::from_json(&json_str).map_err(|e| e.to_string())?;
        Ok(Some(config))
    }

    pub fn insert_token_usage_record(
        &self,
        record: &crate::models::TokenUsageRecord,
    ) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO token_usage_history
                (id, agent_id, conversation_id, timestamp, model, provider, tokens_in, tokens_out, cost_usd)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
            rusqlite::params![
                &record.id,
                &record.agent_id,
                &record.conversation_id,
                &record.timestamp,
                &record.model,
                &record.provider,
                &record.tokens_in,
                &record.tokens_out,
                &record.cost_usd
            ],
        )?;
        Ok(())
    }

    pub fn get_token_usage_history(
        &self,
        agent_id: Option<&str>,
        conversation_id: Option<&str>,
        days: u32,
    ) -> SqlResult<Vec<crate::models::TokenUsageRecord>> {
        let conn = self.conn.lock().unwrap();

        let cutoff = chrono::Utc::now() - chrono::Duration::days(days as i64);
        let cutoff_str = cutoff.to_rfc3339();

        let mut query = String::from(
            "SELECT id, agent_id, conversation_id, timestamp, model, provider, tokens_in, tokens_out, cost_usd
             FROM token_usage_history
             WHERE timestamp >= ?1"
        );

        let mut sql_params: Vec<&dyn rusqlite::ToSql> = vec![&cutoff_str];
        let mut next_param_idx = 2;

        if let Some(ref a_id) = agent_id {
            query.push_str(&format!(" AND agent_id = ?{}", next_param_idx));
            sql_params.push(a_id);
            next_param_idx += 1;
        }

        if let Some(ref c_id) = conversation_id {
            query.push_str(&format!(" AND conversation_id = ?{}", next_param_idx));
            sql_params.push(c_id);
            next_param_idx += 1;
        }

        query.push_str(" ORDER BY timestamp ASC");

        let mut stmt = conn.prepare(&query)?;

        let rows = stmt.query_map(rusqlite::params_from_iter(sql_params), |row| {
            Ok(crate::models::TokenUsageRecord {
                id: row.get(0)?,
                agent_id: row.get(1)?,
                conversation_id: row.get(2)?,
                timestamp: row.get(3)?,
                model: row.get(4)?,
                provider: row.get(5)?,
                tokens_in: row.get(6)?,
                tokens_out: row.get(7)?,
                cost_usd: row.get(8)?,
            })
        })?;

        let mut records = Vec::new();
        for row in rows {
            records.push(row?);
        }
        Ok(records)
    }

    pub fn get_system_warnings(&self) -> SqlResult<Vec<crate::models::SystemWarning>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, agent_id, timestamp, warning_type, message, resolved 
             FROM system_warnings 
             WHERE resolved = 0 
             ORDER BY timestamp DESC",
        )?;

        let rows = stmt.query_map([], |row| {
            Ok(crate::models::SystemWarning {
                id: row.get(0)?,
                agent_id: row.get(1)?,
                timestamp: row.get(2)?,
                warning_type: row.get(3)?,
                message: row.get(4)?,
                resolved: row.get(5)?,
            })
        })?;

        let mut warnings = Vec::new();
        for row in rows {
            warnings.push(row?);
        }
        Ok(warnings)
    }

    pub fn resolve_system_warning(&self, warning_id: &str) -> SqlResult<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE system_warnings SET resolved = 1 WHERE id = ?1",
            rusqlite::params![warning_id],
        )?;
        Ok(())
    }
}

// ─── Helper Functions ────────────────────────────────────────────────────────

fn status_to_string(status: &AgentStatus) -> String {
    match status {
        AgentStatus::Active => "active".to_string(),
        AgentStatus::Sleeping => "sleeping".to_string(),
        AgentStatus::Thinking => "thinking".to_string(),
        AgentStatus::Stopped => "stopped".to_string(),
        AgentStatus::Error => "error".to_string(),
    }
}

fn string_to_status(s: &str) -> AgentStatus {
    match s {
        "active" => AgentStatus::Active,
        "sleeping" => AgentStatus::Sleeping,
        "thinking" => AgentStatus::Thinking,
        "stopped" => AgentStatus::Stopped,
        "error" => AgentStatus::Error,
        _ => AgentStatus::Stopped,
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_db() -> Database {
        let conn = Connection::open_in_memory().unwrap();
        let db = Database {
            conn: Mutex::new(conn),
        };
        db.run_migrations().unwrap();
        db
    }

    #[test]
    fn test_agent_crud() {
        let db = create_test_db();

        let agent = Agent {
            id: "test-agent-1".to_string(),
            name: "Test Agent".to_string(),
            role: "analyst".to_string(),
            emoji: "🤖".to_string(),
            color: "#FF0000".to_string(),
            status: AgentStatus::Active,
            isolated: false,
            paused: false,
            container_id: Some("container-1".to_string()),
            personality: AgentPersonality {
                name: "Curious".to_string(),
                communication_style: "direct".to_string(),
                expertise: vec!["analysis".to_string()],
                guardrails: vec!["no-code".to_string()],
                custom_instructions: "Be helpful".to_string(),
                active_model: None,
                soul_template: None,
                identity_template: None,
            },
            capabilities: AgentCapabilities::default(),
            integrations: vec!["slack".to_string()],
            visual_identity: None,
            memories: vec![],
            created_at: Utc::now(),
            stats: AgentStats::default(),
        };

        // Insert
        db.insert_agent(&agent).unwrap();

        // Read
        let retrieved = db.get_agent("test-agent-1").unwrap();
        assert!(retrieved.is_some());
        assert_eq!(retrieved.unwrap().name, "Test Agent");

        // List
        let all = db.list_agents().unwrap();
        assert_eq!(all.len(), 1);

        // Update
        let mut updated_agent = agent.clone();
        updated_agent.name = "Updated Agent".to_string();
        db.update_agent(&updated_agent).unwrap();

        let retrieved_updated = db.get_agent("test-agent-1").unwrap().unwrap();
        assert_eq!(retrieved_updated.name, "Updated Agent");

        // Delete
        db.delete_agent("test-agent-1").unwrap();
        let deleted = db.get_agent("test-agent-1").unwrap();
        assert!(deleted.is_none());
    }

    #[test]
    fn test_message_operations() {
        let db = create_test_db();

        let agent = Agent {
            id: "agent-1".to_string(),
            name: "Agent 1".to_string(),
            role: "analyst".to_string(),
            emoji: "🤖".to_string(),
            color: "#FF0000".to_string(),
            status: AgentStatus::Active,
            isolated: false,
            paused: false,
            container_id: None,
            personality: AgentPersonality {
                name: "Agent 1".to_string(),
                communication_style: "direct".to_string(),
                expertise: vec![],
                guardrails: vec![],
                custom_instructions: "".to_string(),
                active_model: None,
                soul_template: None,
                identity_template: None,
            },
            capabilities: AgentCapabilities::default(),
            integrations: vec![],
            visual_identity: None,
            memories: vec![],
            created_at: Utc::now(),
            stats: AgentStats::default(),
        };
        db.insert_agent(&agent).unwrap();

        let conv_id = db.get_or_create_conversation("agent-1").unwrap();
        assert!(!conv_id.is_empty());

        let msg_id = db.insert_message(&conv_id, "user", "Hello").unwrap();
        assert!(!msg_id.is_empty());

        db.insert_message(&conv_id, "assistant", "Hi there")
            .unwrap();

        let messages = db.get_messages(&conv_id, 10).unwrap();
        assert_eq!(messages.len(), 2);
        assert_eq!(messages[0].role, "user");
        assert_eq!(messages[1].role, "assistant");
    }

    #[test]
    fn test_bridge_operations() {
        let db = create_test_db();

        let agent = Agent {
            id: "agent-1".to_string(),
            name: "Agent 1".to_string(),
            role: "analyst".to_string(),
            emoji: "🤖".to_string(),
            color: "#FF0000".to_string(),
            status: AgentStatus::Active,
            isolated: false,
            paused: false,
            container_id: None,
            personality: AgentPersonality {
                name: "Agent 1".to_string(),
                communication_style: "direct".to_string(),
                expertise: vec![],
                guardrails: vec![],
                custom_instructions: "".to_string(),
                active_model: None,
                soul_template: None,
                identity_template: None,
            },
            capabilities: AgentCapabilities::default(),
            integrations: vec![],
            visual_identity: None,
            memories: vec![],
            created_at: Utc::now(),
            stats: AgentStats::default(),
        };
        db.insert_agent(&agent).unwrap();

        let bridge = Bridge {
            id: "bridge-1".to_string(),
            agent_id: "agent-1".to_string(),
            name: "Test Bridge".to_string(),
            bridge_type: BridgeType::Slack,
            enabled: true,
            config: BridgeConfig {
                scope: json!({"channel": "general"}),
                expires_at: None,
                push_enabled: true,
            },
            permissions: BridgePermissions {
                read: true,
                write: true,
                delete: false,
            },
        };

        db.insert_bridge(&bridge).unwrap();

        let retrieved = db.get_bridge("bridge-1").unwrap();
        assert!(retrieved.is_some());

        let agent_bridges = db.list_bridges("agent-1").unwrap();
        assert_eq!(agent_bridges.len(), 1);

        db.delete_bridge("bridge-1").unwrap();
        let deleted = db.get_bridge("bridge-1").unwrap();
        assert!(deleted.is_none());
    }

    #[test]
    fn test_audit_log() {
        let db = create_test_db();

        db.log_audit("agent-1", "created", Some("slack"), "Agent created", None)
            .unwrap();
        db.log_audit("agent-1", "updated", None, "Agent config changed", None)
            .unwrap();

        let entries = db.get_audit_log(Some("agent-1"), 10).unwrap();
        assert_eq!(entries.len(), 2);

        let all_entries = db.get_audit_log(None, 10).unwrap();
        assert_eq!(all_entries.len(), 2);
    }

    #[test]
    fn test_budget_operations() {
        let db = create_test_db();

        let agent = Agent {
            id: "agent-1".to_string(),
            name: "Agent 1".to_string(),
            role: "analyst".to_string(),
            emoji: "🤖".to_string(),
            color: "#FF0000".to_string(),
            status: AgentStatus::Active,
            isolated: false,
            paused: false,
            container_id: None,
            personality: AgentPersonality {
                name: "Agent 1".to_string(),
                communication_style: "direct".to_string(),
                expertise: vec![],
                guardrails: vec![],
                custom_instructions: "".to_string(),
                active_model: None,
                soul_template: None,
                identity_template: None,
            },
            capabilities: AgentCapabilities::default(),
            integrations: vec![],
            visual_identity: None,
            memories: vec![],
            created_at: Utc::now(),
            stats: AgentStats::default(),
        };
        db.insert_agent(&agent).unwrap();

        let budget = AgentBudget {
            agent_id: "agent-1".to_string(),
            payments_enabled: true,
            auto_approve_threshold_cents: 5000,
            per_transaction_limit_cents: 10000,
            daily_limit_cents: 50000,
            monthly_limit_cents: 500000,
            allowed_categories: vec!["software".to_string()],
            daily_spent_cents: 1000,
            monthly_spent_cents: 5000,
            require_approval_new_merchant: true,
            require_approval_recurring: false,
        };

        db.upsert_budget(&budget).unwrap();

        let retrieved = db.get_budget("agent-1").unwrap();
        assert!(retrieved.is_some());
        assert_eq!(retrieved.unwrap().daily_spent_cents, 1000);

        db.update_agent_spending("agent-1", 500, true, true)
            .unwrap();

        let updated = db.get_budget("agent-1").unwrap().unwrap();
        assert_eq!(updated.daily_spent_cents, 1500);
        assert_eq!(updated.monthly_spent_cents, 5500);
    }
}
